version: '3'

services:

  backend:
    build: ./backend
    volumes:
      - ./backend:/var/backend
      - backend_static_files:/var/backend/static
    env_file:
      - config/django_settings
    expose:
      - "8000"
    networks:
      - main
    depends_on:
      - db

  db:
    image: postgres:13
    env_file:
      - config/database_env
    networks:
      - main
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/var/frontend
      - frontend_static_files:/var/frontend/build/static
    expose:
      - "3000"
    depends_on:
      - backend
    networks:
      - main
    command: serve -s build -l 3000

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - backend_static_files:/usr/src/backend/static
      - frontend_static_files:/usr/src/frontend/static
    depends_on:
      - backend
      - frontend
    networks:
      - main

networks:
   main:
     driver: bridge

volumes:
  backend_static_files:
  frontend_static_files:


